export enum DomainError {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  WALLET_NOT_FOUND = "WALLET_NOT_FOUND",
  WALLET_ALREADY_EXISTS = "WALLET_ALREADY_EXISTS",
  INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE",
  INVALID_AMOUNT = "INVALID_AMOUNT",
}
